//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCTFControlPersonal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCTFControlPersonal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_symbol {
            get {
                object obj = ResourceManager.GetObject("delete-symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LCTF_COLOR {
            get {
                object obj = ResourceManager.GetObject("LCTF_COLOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;border-collapse: collapse; width: 100%; height: 54px;&quot; border=&quot;1&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr style=&quot;height: 18px;&quot;&gt;
        ///&lt;td style=&quot;width: 13.6234%; text-align: center; height: 18px;&quot;&gt;Trabajador&lt;/td&gt;
        ///&lt;td style=&quot;width: 13.0831%; height: 18px;&quot;&gt;@dia1&lt;/td&gt;
        ///&lt;td style=&quot;width: 15.9841%; height: 18px;&quot;&gt;@dia2&lt;/td&gt;
        ///&lt;td style=&quot;width: 14.107%; height: 18px;&quot;&gt;@dia3&lt;/td&gt;
        ///&lt;td style=&quot;width: 12.7418%; height: 18px;&quot;&gt;@dia4&lt;/td&gt;
        ///&lt;td style=&quot;width: 13.4527%; height: 18px;&quot;&gt;@dia5&lt;/td&gt;
        ///&lt;td style=&quot;width: 9.69854%; height: 18p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabla_cuerpo {
            get {
                return ResourceManager.GetString("tabla_cuerpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr style=&quot;height: 18px;&quot;&gt;
        ///&lt;td style=&quot;width: 13.6234%; text-align: center; height: 18px;&quot;&gt;@nombre&lt;/td&gt;
        ///&lt;td style=&quot;width: 13.0831%; height: 18px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;td style=&quot;width: 15.9841%; height: 18px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;td style=&quot;width: 14.107%; height: 18px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;td style=&quot;width: 12.7418%; height: 18px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;td style=&quot;width: 13.4527%; height: 18px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;td style=&quot;width: 9.69854%; height: 18px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string tabla_relleno_emp {
            get {
                return ResourceManager.GetString("tabla_relleno_emp", resourceCulture);
            }
        }
    }
}
